package com.kindai.app.ui.navigation

object Routes {
    const val SPLASH = "splash"
    const val ONBOARDING = "onboarding"
    const val LOGIN = "login"
    const val REGISTER = "register"
    const val CHANGE_PASSWORD = "change_password"
    const val CAREGIVER_HOME = "caregiver_home"
    const val ELDERLY_OWN_HOME = "elderly_own_home"
    const val ADD_PERSON = "add_person"
    const val DASHBOARD = "dashboard/{elderlyId}"
    const val ELDERLY_SIMPLE = "elderly_simple/{elderlyId}"
    const val ADD_HEALTH = "add_health/{elderlyId}?mode={mode}"
    const val AI_ASSESSMENT = "ai_assessment/{elderlyId}?mode={mode}"
    const val ALERTS = "alerts/{elderlyId}"
    const val MEDICATIONS = "medications/{elderlyId}"
    const val SETTINGS = "settings"
    const val HEALTH_SOURCES = "health_sources"
    const val HEALTH_CONNECT = "health_connect"
    const val DEVICES = "devices"
    const val ELDERLY_SOS = "elderly_sos"
    const val ELDERLY_TRENDS = "elderly_trends"
    const val ELDERLY_DOCTOR_SUMMARY = "elderly_doctor_summary"
    const val ELDERLY_DEVICES = "elderly_devices"

    // ── Diabetes routes ───────────────────────────────────────────────────────
    const val DIABETES_HOME           = "diabetes_home"
    const val DIABETES_SETUP          = "diabetes_setup"
    const val ADD_GLUCOSE             = "add_glucose"
    const val GLUCOSE_HISTORY         = "glucose_history"
    const val DIABETES_MEDS           = "diabetes_meds"
    const val ADD_DIABETES_MED        = "add_diabetes_med"
    const val DIABETES_AI             = "diabetes_ai"
    const val DIABETES_TRENDS         = "diabetes_trends"
    const val DIABETES_DOCTOR_SUMMARY = "diabetes_doctor_summary"
    const val DIABETES_ALERTS         = "diabetes_alerts"
    const val DIABETES_SOS            = "diabetes_sos"
    const val FAMILY_SHARING          = "family_sharing"

    fun dashboard(elderlyId: String) = "dashboard/$elderlyId"
    fun elderlySimple(elderlyId: String) = "elderly_simple/$elderlyId"
    fun addHealth(elderlyId: String, mode: String = "detailed") = "add_health/$elderlyId?mode=$mode"
    fun aiAssessment(elderlyId: String, mode: String = "caregiver") = "ai_assessment/$elderlyId?mode=$mode"
    fun alerts(elderlyId: String) = "alerts/$elderlyId"
    fun medications(elderlyId: String) = "medications/$elderlyId"
}
